/**
 * This file has been autogenerated as it didn't exist or was made for an older
 * incompatible version.
 *
 * This file can be used for manual configuration. It will not be modified
 * if the flowDefaults constant exists.
 */
const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');

const WebpackLiveReloadPlugin = require('webpack-livereload-plugin');
const HtmlWebpackTagsPlugin = require('html-webpack-tags-plugin');

const devMode = process.argv.find(v => v.indexOf('webpack-dev-server') >= 0);

/**
 * To change the webpack config, add a new configuration object in
 * the merge arguments below:
 */
module.exports = merge(flowDefaults,
  // Override default configuration
  {
    // mode: 'development',
    // devtool: 'inline-source-map',
  },

  // Add a custom plugin
  {
    plugins: [
      // The LiveReload client from /livereload.js does not support
      // being loaded twice (even from different origins).
      //
      // In order to have Live Reload both for FE and BE code,
      // please also install the LiveReload browser extention in
      // addition to the line below
      devMode && new WebpackLiveReloadPlugin({
        port: 35730
      }),
      devMode && new HtmlWebpackTagsPlugin({
        scripts: [
          'http://localhost:35730/livereload.js', // Webpack Dev Server
          // 'http://localhost:35729/livereload.js', // Spring Boot
        ],
        publicPath: false
      }),
    ]
  },
);
